"""added page filename column in page table

Revision ID: 21365968b96d
Revises: 8b86858b3284
Create Date: 2023-01-12 12:54:11.044074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21365968b96d'
down_revision = '8b86858b3284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
