"""adding html string column in tablelogs

Revision ID: 5d2871611a07
Revises: 6778b2e66fb9
Create Date: 2023-01-19 09:51:46.704617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2871611a07'
down_revision = '6778b2e66fb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TableLogs', sa.Column('html_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TableLogs', 'html_string')
    # ### end Alembic commands ###
