"""create TE tables with changes pk

Revision ID: 642ab64a3e8d
Revises: e74ab30295c5
Create Date: 2023-01-16 20:35:20.888606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '642ab64a3e8d'
down_revision = 'e74ab30295c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TableLogs',
    sa.Column('pageid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tableid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('conf', sa.Float(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('table_img_save_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pageid'], ['PageLogs.pageid'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('tableid')
    )
    op.create_table('CellLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tableid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('left_img', sa.Integer(), nullable=True),
    sa.Column('top_img', sa.Integer(), nullable=True),
    sa.Column('right_img', sa.Integer(), nullable=True),
    sa.Column('down_img', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('left_table', sa.Integer(), nullable=True),
    sa.Column('top_table', sa.Integer(), nullable=True),
    sa.Column('right_table', sa.Integer(), nullable=True),
    sa.Column('down_table', sa.Integer(), nullable=True),
    sa.Column('conf', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tableid'], ['TableLogs.tableid'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RowColLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_col_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tableid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('left_img', sa.Integer(), nullable=True),
    sa.Column('top_img', sa.Integer(), nullable=True),
    sa.Column('right_img', sa.Integer(), nullable=True),
    sa.Column('down_img', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('left_table', sa.Integer(), nullable=True),
    sa.Column('top_table', sa.Integer(), nullable=True),
    sa.Column('right_table', sa.Integer(), nullable=True),
    sa.Column('down_table', sa.Integer(), nullable=True),
    sa.Column('conf', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tableid'], ['TableLogs.tableid'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('FileLogs', sa.Column('region', sa.String(), nullable=True))
    op.add_column('PageLogs', sa.Column('width_TE', sa.Integer(), nullable=True))
    op.add_column('PageLogs', sa.Column('height_TE', sa.Integer(), nullable=True))
    op.add_column('PageLogs', sa.Column('Number_of_Tables', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PageLogs', 'Number_of_Tables')
    op.drop_column('PageLogs', 'height_TE')
    op.drop_column('PageLogs', 'width_TE')
    op.drop_column('FileLogs', 'region')
    op.drop_table('RowColLogs')
    op.drop_table('CellLogs')
    op.drop_table('TableLogs')
    # ### end Alembic commands ###
