"""added predicted and filtered page columns in FileLogs

Revision ID: 6a9ab9b55970
Revises: 7dbf19bc8efb
Create Date: 2023-01-11 14:00:02.654660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a9ab9b55970'
down_revision = '7dbf19bc8efb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileLogs', sa.Column('predicted_cbs_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('FileLogs', sa.Column('predicted_cpl_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('FileLogs', sa.Column('predicted_ccf_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('FileLogs', sa.Column('filtered_cbs_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('FileLogs', sa.Column('filtered_cpl_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('FileLogs', sa.Column('filtered_ccf_pages', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FileLogs', 'filtered_ccf_pages')
    op.drop_column('FileLogs', 'filtered_cpl_pages')
    op.drop_column('FileLogs', 'filtered_cbs_pages')
    op.drop_column('FileLogs', 'predicted_ccf_pages')
    op.drop_column('FileLogs', 'predicted_cpl_pages')
    op.drop_column('FileLogs', 'predicted_cbs_pages')
    # ### end Alembic commands ###
