"""added classification tables

Revision ID: 7dbf19bc8efb
Revises: cf91444fc06a
Create Date: 2023-01-10 16:37:27.669156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbf19bc8efb'
down_revision = 'cf91444fc06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
