"""added page filename column in page table

Revision ID: 8b86858b3284
Revises: 6a9ab9b55970
Create Date: 2023-01-12 12:53:20.330404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b86858b3284'
down_revision = '6a9ab9b55970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PageLogs', sa.Column('page_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PageLogs', 'page_filename')
    # ### end Alembic commands ###
