"""added confidence column in ocrdump

Revision ID: 923e95beb63f
Revises: 21365968b96d
Create Date: 2023-01-12 15:20:44.851736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923e95beb63f'
down_revision = '21365968b96d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OCRDump', sa.Column('conf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OCRDump', 'conf')
    # ### end Alembic commands ###
