"""removing not null constraint

Revision ID: e74ab30295c5
Revises: 923e95beb63f
Create Date: 2023-01-13 10:33:34.076391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74ab30295c5'
down_revision = '923e95beb63f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FileLogs', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('FileLogs', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('FileLogs', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PageLogs', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PageLogs', 'page_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PageLogs', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PageLogs', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PageLogs', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PageLogs', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PageLogs', 'page_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PageLogs', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('FileLogs', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('FileLogs', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('FileLogs', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
